name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Messager
        run: chmod +x ./scripts/python/message.py
      - name: Send build notification
        run: echo "front-end 开始构建和上传" | ./scripts/python/message.py
      - name: Change node env
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://registry.npm.taobao.org
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: upload
        env:
          AK: ${{ secrets.AK }}
          SK: ${{ secrets.SK }}
        run: ls -al && chmod +x uploadoss.sh && ./uploadoss.sh
      - name: Complete notification
        run: echo "front-end构建+上传CDN完成" | ./scripts/python/message.py
